README.md, data_export/bulk_upload.py, docs/creating-studies.md, docs/sharing-data.md
- Documentation of the new hard restrictions
- I also got a little more consistent about bolding vs caps on the hard requirements while I was in there
- Added the bulk uploader, and a new doc targeting uploading data
- Nit on underscore vs space in the main readme.
=> Docs updates, uploader

.github/workflows/pages.yaml
=> fix: add missing comma to pages workflow

.github/workflows/pypi.yaml, .gitignore, cumulus_library/cli.py, cumulus_library/module_allowlist.json, docs/first-time-setup.md, docs/study-list.md, pyproject.toml, tests/test_cli.py
- Adds an allowlist for autojoining select studies from site-packages
- New docs for exposing this to users. 
- Added error condition reporting if study is not found
- which exposed some tests that weren't really doing much, whoops.
=> Allowlist for pip studies

cumulus_library/studies/core/manifest.toml, cumulus_library/studies/core/medication_request.sql, tests/test_cli.py
This PR makes the following change:
- Adds a basic MedicationRequest table to the tables generated by the core study.
=> Added MedicationRequest core table

pyproject.toml
Increments pyproject.toml version number for release.
=> v0.2.0 release

cumulus_library/studies/core/manifest.toml, cumulus_library/studies/core/medication_request.sql, tests/test_cli.py
- Adds a monthly count table for medicationrequests
- changes table name to match current style (i.e. no underscores introduced in FHIR resource names)
- Fixes typo in core export
=> Basic medicationrequest counts

cumulus_library/studies/core/patient.sql
This adds in the change made during a meeting to make sure we explictly treat missing extension data as unknown in patient tables.
=> Patient table unknown handling

cumulus_library/cli_parser.py, cumulus_library/helper.py, cumulus_library/upload.py, pyproject.toml, tests/test_cli.py
This PR cleans up some testing issues that were missed due to a 'we're out of github minutes' line of thinking.
=> v0.3.0 test/lint cleanup

cumulus_library/cli.py, cumulus_library/studies/core/condition.sql, cumulus_library/studies/core/documentreference.sql, cumulus_library/studies/core/encounter.sql, cumulus_library/studies/core/fhir_define.sql, cumulus_library/studies/core/medication_request.sql, cumulus_library/studies/core/observation_lab.sql, cumulus_library/studies/core/patient.sql, cumulus_library/studies/core/setup.sql, cumulus_library/studies/template/counts.sql, cumulus_library/studies/template/setup.sql, cumulus_library/studies/vocab/icd_legend.sql, cumulus_library/studies/vocab/vocab_icd_builder.py, pyproject.toml
- Everything is now a table #49 #38 
- Caught one dangling usage of the old progress bar in the vocab generator
- Incremented version - i'll cut a bugfix release after this to make things simpler for Regienstrief
=> replace views with tables

cumulus_library/__init__.py, cumulus_library/cli.py, cumulus_library/cli_parser.py, pyproject.toml
This PR adds a --version argument to the CLI for coherence checking.
=> Add --version CLI argument

cumulus_library/studies/core/medication_request.sql
Minor fix for potentially NULL rx_display 
https://github.com/smart-on-fhir/cumulus-library/issues/92
=> fix for potentially null values rx_display

cumulus_library/__init__.py, cumulus_library/studies/core/condition.sql, cumulus_library/template_sql/core_medication.sql.jinja
- Version bump
- Fix for last minute change to condition column name
- Removed userselected detection from non-inline medications due to compatibility issues
=> Condition cleanup, userselected hotfix

cumulus_library/.sqlfluff, cumulus_library/base_table_builder.py, cumulus_library/cli.py, cumulus_library/cli_parser.py, cumulus_library/errors.py, cumulus_library/schema/counts.py, cumulus_library/studies/core/count_core.py, cumulus_library/studies/core/count_core.sql, cumulus_library/studies/core/manifest.toml, cumulus_library/study_parser.py, cumulus_library/template_sql/count.sql.jinja, cumulus_library/template_sql/templates.py, tests/test_cli.py, tests/test_data/study_python_counts_valid/manifest.toml, tests/test_data/study_python_counts_valid/module1.py, tests/test_data/study_python_counts_valid/module2.py, tests/test_data/study_python_counts_valid/test.sql, tests/test_data/study_python_valid/manifest.toml, tests/test_data/study_python_valid/test.sql, tests/test_data/study_valid/manifest.toml, tests/test_data/study_valid/test.sql, tests/test_schema_counts.py, tests/test_study_parser.py, tests/test_templates.py
- Reorg of counts generator to leverage BaseTableBuilder
- Updates CLI to dynamically build counts tables
=> Moved count gen to template

tests/regression/run_regression.py
This PR fixes a var typo and adds a graphic x to an early exit condition.
=> Regression var cleanup

docs/index.md
This PR touches the docs index for repo discovery
=> link docs index to github

cumulus_library/databases.py
Propegate input nulls into output nulls, like most SQL functions do.
=> Handle nulls better in duckdb

cumulus_library/cli_parser.py, cumulus_library/study_parser.py, docs/aws-setup.md, docs/core-study-details.md, docs/creating-sql-with-python.md, docs/creating-studies.md, docs/first-time-setup.md, docs/sharing-data.md, docs/study-list.md, docs/third-party-software-citations.md
I might have more later if this is helpful, but this was a good pausing point for me.
=> docs: some wordsmithing and clarification

cumulus_library/databases.py, docs/creating-studies.md
=> A couple tweaks - handle 'Z' timestamps and adjust docs

cumulus_library/studies/discovery/code_definitions.py
This PR adds medicationrequest codings to the list of code systems to export.
=> Added medicationrequest to discovery

.github/workflows/pages.yaml
=> Update docs upon release

cumulus_library/module_allowlist.json, docs/study-list.md
(And add umls/data_metrics to study allowlist.)
=> Add data-metrics to list of studies

cumulus_library/__init__.py, cumulus_library/actions/cleaner.py, cumulus_library/actions/importer.py, cumulus_library/base_utils.py, cumulus_library/cli.py, cumulus_library/cli_parser.py, cumulus_library/databases.py, cumulus_library/errors.py, docs/first-time-setup.md, tests/test_actions.py, tests/test_cli.py, tests/test_duckdb.py
This adds the following:
- A new subcommand/action for importing previously exported studies
- Some alphasorting of large function blocks
- minor: made all custom exceptions children of CumulusLibraryException
- Added a custom argument param #247
=> Added import action

.github/workflows/ci.yaml, cumulus_library/actions/cleaner.py, cumulus_library/cli.py, tests/test_actions.py, tests/test_cli.py
This fixes a bug where views would not be picked up during the clean action.
It also pulls the trigger on forcing modified files to have full coverage.
=> Updated cleaner to remove views

cumulus_library/actions/cleaner.py, cumulus_library/template_sql/shared_macros/syntax.sql.jinja
This adds a few convenience macros to syntax.jinja.
=> Added or/ilike macros to syntax

README.md
Updates the link to the SMART Health IT landing page.
=> Updated link in readme

docs/workflows.md, docs/workflows/propensity-score-matching.md, docs/workflows/valueset.md
=> Fixed parent for renamed docs

.github/workflows/dependabot.yaml, docs/first-time-setup.md, docs/workflows.md
Two minor nits in the docs and dependabot configuration
=> Added dependabot, docs fixups

cumulus_library/__init__.py
=> minor version bump

cumulus_library/__init__.py, cumulus_library/cli.py
A few dangling prints removed from the last PR
=> Cleanup debug statements

.github/workflows/ci.yaml
This PR addresses #174 by testing pythons from 3.11 upwards.
=> Matrix testing python versions
