- .gitignore
- README.md
- docs/README.md
- docs/aws-setup.md
- docs/core-study-details.md
- docs/creating-studies.md
- docs/first-time-setup.md
- docs/index.md
- docs/sharing-data.md
The main documentation repo ([smart-on-fhir/cumulus](https://github.com/smart-on-fhir/cumulus)) will use jekyll and GitHub Pages to build docs from this repo and others into one main site.
But in order to do that, we need some little jekyll metadata markers and to organize our docs in a specific way.
- Add docs/index.md (intro) and docs/README.md (dev explainer)
- Add metadata like titles and nav order for all docs
Right now, the docs site is rebuilt anytime the main docs repo is changed or on a manual request. But eventually, I will add a GitHub action here that will go poke the main docs repo to rebuild itself, if the docs/ folder here changes.
- Each Cumulus project will have its own little `docs/` fiefdom in its own repo.
- This way, docs can update as code changes more easily.
- …
> docs: prepare the docs/ folder for ingestion by jekyll

- cumulus_library/cli.py
- cumulus_library/study_parser.py
- docs/aws-setup.md
- docs/first-time-setup.md
- pyproject.toml
- Rename `--study_dir` to `--study-dir`
- Drop the S3 bucket gathering entirely, we can get it from workgroup
- Rename `CUMULUS_LIBRARY_SCHEMA` to `CUMULUS_LIBRARY_DATABASE`
- Mention `CUMULUS_LIBRARY_WORKGROUP` in the docs
I could add some safety fallbacks for old env names, if you like the renames, but feel they are too jarring / sudden.
> feat!: update some CLI arguments / env variables for consistency

- cumulus_library/template_sql/extension_denormalize.sql.jinja
- tests/test_templates.py
This PR makes the following chage:
- SqlFluff trims out names of unnests that are used in a where clause, but not in the query itself. This undoes that correction and adds an ignore which should prevent it from happening in the future.
> Undo linter overcorrection

- .github/pull_request_template.md
- .github/workflows/ci.yaml
- docs/study-list.md
- Limits CI runs to just PRs and interrupts runs, and excludes markdown updates
- Trims PR template as an excuse to test the above
> Limited CI runs

- cumulus_library/cli.py
- cumulus_library/errors.py
- cumulus_library/study_parser.py
Adds support for global AWS env settings #20 
Moves existing custom error into cumulus_library.errors #3
> Read AWS creds from profile, central error lib

- cumulus_library/__init__.py
- cumulus_library/template_sql/codeable_concept_denormalize.sql.jinja
- tests/test_templates.py
This improves the codableConcept query for large datasets by moving the ordering step to the partitioned subtable, so it can be better map/reduced.
- [X ] Consider if documentation (like in `docs/`) needs to be updated
> performance tuning for codeableConcepts

- cumulus_library/studies/core/builder_encounter_coding.py
- cumulus_library/studies/core/builder_encounter_coding.sql
1. when OID system is used, must include prefix "urn:oid:" 
2. valuesets are not codesystem, thusly removed valueset
> Urn oid namespace for coding "SYSTEM"

- cumulus_library/template_sql/core_medication.sql.jinja
- cumulus_library/template_sql/templates.py
This PR makes the following change:
- flips the template infrastructure for core_medication from `missing_selected` to `has_selected` to match the invocation in the builder.
> flipped userselected detection in templates

- cumulus_library/studies/core/manifest.toml
- cumulus_library/studies/core/version.sql
- cumulus_library/upload.py
- tests/test_cli.py
This PR makes the following change:
- Added new core__meta_version table with basic version number (i.e. major only)
- Upload will now look for an exported {study}__meta_version table
- If found, will add version to aggregator post. If not, will assume no version (i.e. version 0)
This is one half of the implementation for versioning - the other half is at [this aggregator PR](https://github.com/smart-on-fhir/cumulus-aggregator/pull/99).
> Added core versioning

- cumulus_library/studies/core/builder_condition_codeableconcept.py
- cumulus_library/studies/core/builder_core_medication.py
- cumulus_library/studies/core/builder_encounter_coding.py
- cumulus_library/studies/core/condition.sql
- cumulus_library/studies/core/condition_codeable_concept.sql
- cumulus_library/template_sql/codeable_concept_denormalize.sql.jinja
- cumulus_library/template_sql/templates.py
- tests/test_cli.py
- tests/test_templates.py
- adds a flag to allow codeable concepts tables to be priority filtered (i.e select the first found code, primarily for display reasons for core summary statistics) or just dump all found codes
- Adds both instances of these tables for condition
- Removes code from the core__condition table
- The intent by now basically requiring a left join against one of the coding tables is to eliminate accidental double counting - this will require some work on the analyst's part
- condition__count now points at the explicitly filtered code list.
> flattened conditions, added new code table

- cumulus_library/base_table_builder.py
This PR removes a second instance of array indexing in the base_table_builder, which was causing us to search only the first character of a potential string for a name like `"schema"."table"`
This is currently only an issue when we are creating a completely empty table.
> Removed extra indexing on schema removal

- cumulus_library/cli.py
This PR addresses #108 by recursively searching for manifest files, rather than assuming the user is running this search in a specific place.
> Better discovery of manifest location

- cumulus_library/upload.py
- tests/test_cli.py
This PR updates the upload `--target` argument to actually filter the list of files to upload
> Added upload check for targets

- .pre-commit-config.yaml
- .sqlfluffignore
- cumulus_library/studies/core/documentreference.sql
- cumulus_library/studies/core/encounter.sql
- cumulus_library/studies/core/fhir_lookup_tables.sql
- cumulus_library/studies/core/fhir_mapping_tables.sql
- cumulus_library/studies/core/medication_request.sql
- cumulus_library/studies/core/observation.sql
- cumulus_library/studies/core/observation_lab.sql
- cumulus_library/studies/core/observation_vital_signs.sql
- cumulus_library/studies/core/patient.sql
- cumulus_library/studies/core/patient_extensions.sql
- cumulus_library/studies/core/setup.sql
- cumulus_library/studies/core/study_period.sql
- cumulus_library/studies/template/counts.sql
- cumulus_library/studies/vocab/icd_legend.sql
- cumulus_library/template_sql/code_system_pairs.sql.jinja
- cumulus_library/template_sql/codeable_concept_denormalize.sql.jinja
- cumulus_library/template_sql/core_medication.sql.jinja
- cumulus_library/template_sql/create_view_as.sql.jinja
- cumulus_library/template_sql/ctas.sql.jinja
- cumulus_library/template_sql/ctas_empty.sql.jinja
- cumulus_library/template_sql/extension_denormalize.sql.jinja
- cumulus_library/template_sql/show_tables.sql.jinja
- cumulus_library/template_sql/show_views.sql.jinja
- pyproject.toml
- tests/test_templates.py
- Uprevs pandas #127 
- Updates SqlFluff to latest version 
- This removes the need for all our current rule exceptions (thank god)
- Global rerun (the bulk of changes in this PR
> Uprev pandas/sqlfluff

- cumulus_library/cli.py
- cumulus_library/cli_parser.py
- cumulus_library/study_parser.py
- tests/test_cli.py
- tests/test_study_parser.py
- Asks for confirmation when using the `--prefix` argument #129 
- Adds a `--continue` param for specifying a point in the manifest's list of SQL files to continue a build from (useful for debugging errors that occur at near the end of a build)
- As a result of doing this, cleaned up some places where clean wasn't quite wired into reading a prefix directly from a manifest
> Confirm drop by prefix, add --continue

- cumulus_library/__init__.py
- cumulus_library/template_sql/code_system_pairs.sql.jinja
- tests/test_templates.py
This PR cleans up some missing quotes in the code pairs template.
> fix quoting in code pair template

- cumulus_library/databases.py
I just forgot about Medication because it's a weird little generated table from ETL.
> feat: add Medication to duckdb schema list

- cumulus_library/databases.py
Don't require a timezone with our parsed timestamps (otherwise, we can't parse a timestamp like YYYY-MM-DD).
And make sure to ask Pandas to use modern nullable columns instead of coerced-float columns when there are nullable-int datasets (like you see if you have a powerset output table with an integer column).
> fix: fix naive timestamps and int types in duckdb

- cumulus_library/databases.py
This is how Athena handles them.
> fix(duckdb): skip nulls inside array for array_join()

- cumulus_library/databases.py
- tests/test_duckdb.py
> Fix duckdb's from_iso8601_timestamp() to handle just-year timestamps

- cumulus_library/studies/core/builder_documentreference.py
- cumulus_library/studies/core/core_templates/documentreference.sql.jinja
- cumulus_library/studies/core/core_templates/patient.sql.jinja
- tests/test_core.py
- tests/testbed_utils.py
I found these while working on tests for a different upcoming PR.
> A couple miscellaneous fixes

- cumulus_library/statistics/counts.py
- tests/test_counts_builder.py
This updates the subject field generated by the counts builder to match the correct v2 name.
> Updated name of patient count field in stats

- cumulus_library/cli.py
- cumulus_library/upload.py
- tests/test_cli.py
- Switches to the builtin response.raise_for_status() function for error generation on rejected uploads for nicer formatting
- Catches the RequestException gracefully rather than dumping a stack trace
> Improved upload error reporting

- cumulus_library/.sqlfluff
- cumulus_library/databases.py
- cumulus_library/db_config.py
- cumulus_library/template_sql/base_templates.py
- tests/test_data/study_python_local_template/local_template.py
- tests/test_data/study_python_local_template/manifest.toml
- tests/test_data/study_python_local_template/module1.py
- tests/test_data/study_python_local_template/table.sql.jinja
- tests/test_duckdb.py
- tests/test_study_parser.py
This commit adds a module for storing information about the type of database requested via the CLI.
This is planned to be replaced the next time we make a breaking change: #225
> Track db type for jinja templates

- cumulus_library/apis/umls.py
- cumulus_library/base_utils.py
- cumulus_library/cli.py
- cumulus_library/cli_parser.py
- cumulus_library/databases.py
- cumulus_library/db_config.py
- cumulus_library/statistics/psm.py
- cumulus_library/studies/vocab/README.MD
- cumulus_library/studies/vocab/vocab_icd_builder.py
- cumulus_library/study_parser.py
- docs/creating-sql-with-python.md
- docs/creating-studies.md
- docs/first-time-setup.md
- docs/study-list.md
- tests/conftest.py
- tests/core/test_core_meds.py
- tests/test_athena.py
- tests/test_data/aws/boto3.client.s3.list_objects_v2.json
- tests/test_psm.py
- tests/test_study_parser.py
- tests/testbed_utils.py
This PR adds a StudyConfig object, which transports values from the CLI down to individual studies, for customizing behavior of study runs.
It also contains several tweaks in support of the UMLS study, and moves the upload logic for databases into each database class.
> StudyConfig infrastructure

- cumulus_library/cli.py
- tests/test_cli.py
A couple args were broken in the 2.1 release:
--umls-key (env var would work, but not CLI arg)
--builder
> Small CLI fixes

- cumulus_library/databases.py
- cumulus_library/studies/core/builder_condition.py
- cumulus_library/studies/core/builder_documentreference.py
- cumulus_library/studies/core/builder_encounter.py
- cumulus_library/studies/core/builder_medication.py
- cumulus_library/studies/core/builder_medicationrequest.py
- cumulus_library/studies/core/builder_observation.py
- cumulus_library/studies/core/builder_patient.py
- cumulus_library/studies/core/core_templates/observation_component_valuequantity.sql.jinja
- cumulus_library/studies/discovery/code_detection.py
- cumulus_library/template_sql/sql_utils.py
- tests/test_template_sql_utils.py
(Instead of erroring out.)
This helps in cases where some tables get optionally created (like the ETL completion tables), because Athena generates an exception for that.
> fix: if a table does not exist, use an empty schema

- cumulus_library/databases.py
- docs/creating-studies.md
- tests/test_duckdb.py
Previously, --load-ndjson-dir would only look for an ETL output-style format like this:
`dir/condition/*.ndjson`
`dir/patient/*.ndjson`
But now it will also look for flat files as well (i.e. ETL input-style format) like this:
dir/1.Patient.ndjson
dir/Patient.october.ndjson
dir/Patient.ndjson
This will make it nicer to use the --load-ndjson-dir flow when you are working on ndjson files directly, without going through Cumulus ETL first.
> Support a flat ndjson dir layout as well as a hierarchical one

- .github/workflows/ci.yaml
- MAINTAINER.md
- cumulus_library/actions/builder.py
- cumulus_library/actions/cleaner.py
- cumulus_library/actions/exporter.py
- cumulus_library/base_table_builder.py
- cumulus_library/base_utils.py
- cumulus_library/cli.py
- cumulus_library/databases.py
- cumulus_library/protected_table_builder.py
- cumulus_library/study_parser.py
- docs/creating-studies.md
- tests/test_athena.py
- tests/test_cli.py
- tests/test_data/study_dedicated_schema/manifest.toml
- tests/test_data/study_dedicated_schema/module1.py
- tests/test_data/study_dedicated_schema/module2.py
- tests/test_data/study_dedicated_schema/test.sql
- tests/test_data/study_valid/manifest.toml
- tests/test_data/study_valid/test2.sql
- tests/test_databases.py
- tests/test_study_parser.py
- Allows a study to specify an explict schema
- Auto transforms table names if this is done - so 'study__table' becomes just 'table', so reverting this is a config-only change
- adds tests for --continue and --builder CLI args, fixing one bug with the former.
- [] Update template repo if there are changes to study configuration
> Allow a study to specify a schema

- CONTRIBUTING.md
- cumulus_library/databases.py
- pyproject.toml
- tests/test_duckdb.py
We now load any ndjson files that cumulus-fhir-support says to.
Depends on https://github.com/smart-on-fhir/cumulus-fhir-support/pull/3
> feat: switch to cumulus-fhir-support's ndjson reading code

- cumulus_library/base_utils.py
- cumulus_library/databases.py
- cumulus_library/log_utils.py
- cumulus_library/module_allowlist.json
- tests/test_athena.py
- Updates 3.0 schema handling for external tables in athena
- Adds `rxnorm` as a target
- cleanup: one irritating print statement, module-based import
> Schema handling for external tables

- cumulus_library/cli.py
- tests/test_cli.py
This allows consumers to not need to check for None - they can just do options.get().
> If no --option is given, provide a bare {} dictionary

- cumulus_library/__init__.py
- cumulus_library/databases.py
- cumulus_library/log_utils.py
- tests/test_logging.py
This PR addresses #259 by altering a given lib_transaction table if an error is raised.
Also added manifest/config to the external API.
> Gracefully migrate transactions

- .github/workflows/ci.yaml
- cumulus_library/actions/builder.py
- cumulus_library/base_utils.py
- cumulus_library/statistics/psm.py
- cumulus_library/study_manifest.py
- pyproject.toml
- tests/core/test_core.py
- tests/test_cli.py
- tests/test_data/parser_mock_data.py
- tests/test_data/study_python_counts_valid/manifest.toml
- tests/test_study_parser.py
- Minimum python is now 3.11 #232
- now uses the stdlib `tomllib` module for parsing #231
> Uprev to 3.11

- cumulus_library/databases/athena.py
- cumulus_library/databases/duckdb.py
Also, fix a small NULL handling issue with array_join in duckdb.
> Fix Athena's ability to export "decimal" types

- cumulus_library/apis/umls.py
- tests/test_data/apis/umls/expansion_valueset.json
- tests/test_umls_api.py
This PR makes the VSAC API support the pagination paramter for the expand operation.
> Iterate through pages in VSAC API

- .github/pull_request_template.md
- cumulus_library/studies/core/reference_sql/builder_condition.sql
- cumulus_library/studies/core/reference_sql/builder_documentreference.sql
- cumulus_library/studies/core/reference_sql/builder_encounter.sql
- cumulus_library/studies/core/reference_sql/builder_medicationrequest.sql
- cumulus_library/studies/core/reference_sql/builder_observation.sql
- cumulus_library/studies/core/reference_sql/builder_patient.sql
- docs/core-study-details.md
- docs/sharing-data.md
- docs/statistics.md
- docs/study-list.md
- docs/third-party-software-citations.md
- docs/writing-sql.md
This addresses the following tickets via documentation:
#147 (along with https://github.com/smart-on-fhir/cumulus/pull/35)
#214
#216
> Deprecate observation notice, optional fields, sql writing guide

- cumulus_library/__init__.py
- cumulus_library/studies/core/builder_condition.py
- cumulus_library/studies/core/builder_documentreference.py
- cumulus_library/studies/core/builder_encounter.py
- cumulus_library/studies/core/builder_medicationrequest.py
- cumulus_library/studies/core/builder_observation.py
- cumulus_library/studies/core/builder_patient.py
- cumulus_library/studies/core/builder_prereq_tables.py
- cumulus_library/studies/core/count_core.py
- cumulus_library/studies/discovery/code_detection.py
- cumulus_library/studies/vocab/vocab_icd_builder.py
- tests/test_data/study_dedicated_schema/module1.py
- tests/test_data/study_dedicated_schema/module2.py
- tests/test_data/study_python_counts_valid/module1.py
- tests/test_data/study_python_counts_valid/module2.py
- tests/test_data/study_python_local_template/module1.py
- tests/test_data/study_python_no_subclass/module1.py
- tests/test_data/study_python_s3/module1.py
- tests/test_data/study_python_s3/module2.py
- tests/test_data/study_python_valid/module1.py
- tests/test_data/study_python_valid/module2.py
- tests/test_discovery.py
> Add BaseTableBuilder and CountsBuilder to the public API

- cumulus_library/cli.py
- cumulus_library/module_allowlist.json
- tests/test_actions.py
- tests/test_cli.py
Previously, we assumed they'd be directories inside site-packages.
But in some cases (like pip install -e . in linux), that installs a .pth file that points at the real location.
So let's just ask Python where these known modules are.
Fixes #290 
> Use python import machinery to find known studies

- docs/creating-studies.md
Plus add a comment to not forget to actually export the tables, which I have done in the past.
> docs: add warning about capping max_date in the meta_date table

- MAINTAINER.md
- cumulus_library/actions/builder.py
- cumulus_library/builders/counts.py
- cumulus_library/cli.py
- cumulus_library/studies/core/count_core.py
- cumulus_library/study_manifest.py
- tests/conftest.py
- tests/test_athena.py
- tests/test_counts_builder.py
- tests/test_data/study_dynamic_prefix/counts.py
- tests/test_data/study_dynamic_prefix/gen_prefix.py
- tests/test_data/study_dynamic_prefix/manifest.toml
- tests/test_data/study_dynamic_prefix/meta.py
- tests/test_dynamic_manifest.py
- tests/testbed_utils.py
- tests/valueset/test_umls.py
This will allow a study to provide a Python file that accepts study options and generates an appropriate study prefix.
It's largely targeted at the data_metrics study, but might have application elsewhere.
> Add an advanced dynamic_study_prefix field to manifests.

- cumulus_library/template_sql/ctas_from_parquet.sql.jinja
- tests/test_base_templates.py
This PR quote-escapes local parquet create table statements, in case those statements contain reserved sql words.
> Quote local parquet CTAS queries

- cumulus_library/__init__.py
- cumulus_library/cli.py
This prevents needing a valid db config to run the generate command.
> Skip DB connection check for prepare mode

- cumulus_library/__init__.py
- cumulus_library/databases/athena.py
- cumulus_library/databases/base.py
- cumulus_library/databases/duckdb.py
- cumulus_library/databases/utils.py
- tests/test_athena.py
- tests/test_cli.py
- tests/test_databases.py
- tests/test_discovery.py
- tests/test_duckdb.py
- tests/test_logging.py
- tests/test_static_file.py
- tests/testbed_utils.py
The automatic db connection is causing some issues for the packaging use case (where we want to generate sql based on db type, but aren't actually using a connection), so this creates an explicit connection function that is called seperately from the database object init. Connection logic is then moved from the individual db init functions to the connect function.
> Breakout connection from athena DB init

- cumulus_library/__init__.py
- cumulus_library/studies/core/core_templates/completion_utils.jinja
- docs/core-study-details.md
> docs: explain which resources are completion tracked

- cumulus_library/studies/core/core_templates/encounter.sql.jinja
- cumulus_library/studies/core/fhir_mapping_tables.sql
- cumulus_library/studies/core/reference_sql/builder_encounter.sql
- cumulus_library/studies/core/reference_sql/builder_prereq_tables.sql
- tests/core/test_core_encounters.py
These codes were not handled, but now are:
- OBSENC (v3)
- I (v2 -> IMP)
- P (v2 -> PRENC)
Additionally, we verify the code system too now.
Fixes: #333
> core: add some missing Encounter.class codes

- cumulus_library/actions/cleaner.py
- pyproject.toml
- tests/test_actions.py
- tests/test_cli.py
- tests/test_data/study_dedicated_schema/module2.py
- Updates the version of duckDB to 1.1.3, which fixes some edge cases in parquet handling that the UMLS study was hitting
- Adds better handling for differences between different DROP statement quote handling in athena vs duckdb
> Better handling for dedicated schemas

- cumulus_library/__init__.py
- cumulus_library/actions/builder.py
- cumulus_library/builders/base_table_builder.py
- cumulus_library/builders/counts.py
- cumulus_library/builders/statistics_templates/counts_templates.py
- cumulus_library/template_sql/base_templates.py
- cumulus_library/template_sql/ctas_from_parquet.sql.jinja
- cumulus_library/template_sql/insert_into.sql.jinja
- tests/test_actions.py
- tests/test_base_templates.py
- tests/test_counts_builder.py
- tests/test_data/study_python_counts_valid/module1.py
- tests/test_data/study_python_counts_valid/module2.py
This PR primarily updates how schemas are handled in duckdb for insert/parquet CTAS cases.
A few minor things that are done along the way:
- Builders now take a manifest as an optional argument #324
- This allows us to skip some jankiness bootstrapping counts builders with a study prefix. Marked this as deprecated.
- Since the `get_base_templates` function is used frequently to get tables in studies with the core macros loaded in, made the function `get_templates` and converted the former to an alias
> Better duckdb schema, manifest/template entrypoint tweaks

- cumulus_library/databases/athena.py
- cumulus_library/databases/base.py
- cumulus_library/databases/duckdb.py
- cumulus_library/databases/utils.py
- pyproject.toml
- tests/test_duckdb.py
- tests/testbed_utils.py
This commit changes how --load-ndjson-dir works, telling DuckDB to load the data from files on disk itself, rather than us loading that data into memory all at once, then handing it to DuckDB.
Which allows querying larger-than-memory data sets.
But... the SQL itself can still be a memory bottleneck, if it requires loading too much data into memory.
> fix: don't load NDJSON data into memory all at once

- cumulus_library/studies/core/reference_sql/builder_allergyintolerance.sql
- cumulus_library/studies/core/reference_sql/builder_condition.sql
- cumulus_library/studies/core/reference_sql/builder_diagnosticreport.sql
- cumulus_library/studies/core/reference_sql/builder_documentreference.sql
- cumulus_library/studies/core/reference_sql/builder_encounter.sql
- cumulus_library/studies/core/reference_sql/builder_medicationrequest.sql
- cumulus_library/studies/core/reference_sql/builder_observation.sql
- cumulus_library/template_sql/base_templates.py
- cumulus_library/template_sql/shared_macros/unnest_utils.jinja
- tests/test_base_templates.py
With DuckDB, row_number() over an unnested field seems to blow up the memory usage, rather than spilling over onto the disk.
So instead, this commit switches the flatten() macro into two branches:
- DuckDB branch: switch to generate_subscripts() which Athena does not have. This is memory-performant.
- Fallback/Athena branch: switch to WITH ORDINALITY which DuckDB does not have. This is simpler code, and DuckDB will hopefully one day support WITH ORDINALITY.
This also fixes a bug where the order of rows was not guaranteed by the SQL engine. This seemed to only affect DuckDB. Now both branches guarantee proper ordering.
- If you've added/removed `core` study fields that not in US Core, update our list of those …
> fix: avoid memory bottlenecks when flattening tables

- MAINTAINER.md
- cumulus_library/actions/builder.py
- cumulus_library/actions/cleaner.py
- cumulus_library/actions/importer.py
- cumulus_library/actions/uploader.py
- cumulus_library/base_utils.py
- cumulus_library/builders/counts.py
- cumulus_library/builders/valueset/vsac.py
- cumulus_library/cli.py
- cumulus_library/databases/duckdb.py
- cumulus_library/databases/utils.py
- pyproject.toml
- tests/conftest.py
- tests/regression/run_regression.py
- tests/test_cli.py
- tests/test_counts_builder.py
- tests/test_data/study_dynamic_prefix/gen_prefix.py
This PR adds the maintenance technical debt of 'check and see if there's a bare print statement before allowing a commit to occur', and implements #350 
> Cutover to rich for all console output

- cumulus_library/__init__.py
- cumulus_library/actions/uploader.py
- tests/test_actions.py
This addresses #306 by casting meta version numbers being of a non-integer numeric type by casting them through floats, then ints, to get them into the expected format for the aggregator.
> better handling of non-integer versions

- cumulus_library/actions/uploader.py
- tests/test_cli.py
Now we'll provide a message about it. Addresses #352 
> Provide feedback if trying to upload zero files

- cumulus_library/actions/builder.py
- cumulus_library/databases/athena.py
- cumulus_library/databases/base.py
- cumulus_library/databases/duckdb.py
- tests/test_actions.py
In cases where an error :might: be related to a database not being initialized by the etl, we'll point out the documentation. Addresses #354 
> Suggest cases where a non-initialized DB may cause errors

- docs/sharing-data.md
This adds a line to the documentation describing the required permissions to export data from Athena.
> Added example IAM permissions for export

- cumulus_library/actions/uploader.py
- cumulus_library/cli.py
- cumulus_library/cli_parser.py
- docs/sharing-data.md
- tests/test_actions.py
This allows a user to specify a network as part of an aggregator upload target.
> Added network arg to upload command

- cumulus_library/studies/discovery/code_definitions.py
- cumulus_library/studies/discovery/discovery_templates/code_system_pairs.sql.jinja
- tests/test_discovery.py
This addresses #361 by adding a new field, `observation.component`, to discovery, and a check for 'do we have a coding that's not in an array'.
> Added obsservation component code detection

- .github/workflows/pypi.yaml
- cumulus_library/__init__.py
- cumulus_library/actions/uploader.py
- cumulus_library/cli.py
- pyproject.toml
- tests/test_cli.py
This addresses #372 by more gracefully exiting when a --target argument is expected.
> Handle empty target arguments

- cumulus_library/databases/athena.py
- tests/test_databases.py
Instead of requiring a bucket/workgroup to use KMS encryption, we'll now allow any valid encryption option, and only throw an error if something is reporting back as unencrypted.
- If you've changed the public API or a class/method that is part of the public api, update `api.md`
> Loosen requirements for workgroup encryption

- cumulus_library/builders/counts.py
- cumulus_library/builders/statistics_templates/count.sql.jinja
- cumulus_library/builders/statistics_templates/counts_templates.py
- tests/test_counts_builder.py
This allows a user to control whether they have already preprocessed documentreferences before counting as part of their study. Addresses #396 
- If you've changed the public API or a class/method that is part of the public api, update `api.md`
> Counting status for docrefs is now optional

- cumulus_library/builders/counts.py
- cumulus_library/builders/statistics_templates/count.sql.jinja
- cumulus_library/builders/statistics_templates/counts_templates.py
- tests/test_counts_builder.py
This cherry picks the docref update onto the hotfix branch.
- If you've changed the public API or a class/method that is part of the public api, update `api.md`
> Counting status for docrefs is now optional (#398)
